services:
  - type: web
    name: tezcode-backend
    env: node
    rootDir: server
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: tezcode-db
          property: connectionString

databases:
  - name: tezcode-db
    plan: free

